# experiment name
EXP_NAME: normal_mod_resnet
# random number seed
SEED: 0
# super resolution magnification factor
SCALE: 4
# run device model
DEVICE_ID: 0

# Model define
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: True
  G:
    NAME: srresnet_x4
    IN_CHANNELS: 1
    OUT_CHANNELS: 1
    CHANNELS: 64
    NUM_RCB: 16
    COMPILED: True

TRAIN:
  DATASET:
    TRAIN_GT_IMAGES_DIR: "/home/jfeggerd/turbo/real_train_normal_splices"

    GT_IMAGE_SIZE: 96

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    PRETRAINED_G_MODEL: ""
    RESUMED_G_MODEL: ""

  # training hyperparameters
  HYP:
    EPOCHS: 30

    IMGS_PER_BATCH: 128
    SHUFFLE: True
    NUM_WORKERS: 8
    PIN_MEMORY: True
    PERSISTENT_WORKERS: False

  OPTIM:
    NAME: Adam
    LR: 0.0001
    BETAS: [0.9, 0.999]
    EPS: 0.0001
    WEIGHT_DECAY: 0.0

  # Loss function
  LOSSES:
    PIXEL_LOSS:
      NAME: MSELoss
      WEIGHT: [1.0]

  PRINT_FREQ: 100

TEST:
  DATASET:
    PAIRED_TEST_GT_IMAGES_DIR: "/home/jfeggerd/turbo/real_hr_test_normal"
    PAIRED_TEST_LR_IMAGES_DIR: "/home/jfeggerd/turbo/real_lr_test_normal"

  # Test hyperparameters
  HYP:
    IMGS_PER_BATCH: 1
    SHUFFLE: False
    NUM_WORKERS: 1
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  # Only test Y channel
  ONLY_TEST_Y_CHANNEL: True

  SAVE_IMAGE_DIR: "/home/jfeggerd/turbo/train_imgs"
